"""
pr_creator.py
──────────────
Takes a dict of {file_path: new_content} and an AzureDevOpsClient, then:
  1. Creates a new branch
  2. Commits every changed file (one commit per file for simplicity)
  3. Opens a Pull Request with a rich description
"""

import logging
from datetime import datetime, timezone

from azure_devops_client import AzureDevOpsClient

log = logging.getLogger(__name__)

_PR_BODY_TEMPLATE = """\
## 🤖 AI Code Review — Automated Pull Request

> Generated by the **Azure DevOps AI Code Review Agent** using [Qwen2.5-Coder-3B-Instruct](https://huggingface.co/Qwen/Qwen2.5-Coder-3B-Instruct-GGUF) running locally via `llama_cpp`.

---

### Review mode: `{mode}`

| Metric | Value |
|--------|-------|
| Files analysed | {total_files} |
| Files changed | {changed_files} |
| Timestamp | {timestamp} |

---

### Changes per file

{file_sections}

---

> ⚠️ **Please review all changes carefully before merging.**
> This PR was generated automatically. The AI model may make mistakes.
"""

_FILE_SECTION_TEMPLATE = """\
<details>
<summary><code>{path}</code></summary>

{summary}

</details>
"""


class PRCreator:
    def __init__(self, azdo: AzureDevOpsClient):
        self.azdo = azdo

    def create_pr(
        self,
        base_branch: str,
        pr_branch: str,
        mode: str,
        changes: dict[str, str],       # path → new_content
        summaries: dict[str, str],     # path → human summary
        total_files_analysed: int | None = None,
    ) -> str:
        """
        Push all changed files to a new branch and open a Pull Request.
        Returns the PR web URL.
        """
        if not changes:
            raise ValueError("No changes to commit.")

        # 1. Create branch
        log.info(f"Creating branch '{pr_branch}' from '{base_branch}' …")
        self.azdo.create_branch(pr_branch, base_branch)

        # 2. Commit each file
        for i, (path, new_content) in enumerate(changes.items(), 1):
            log.info(f"  Committing [{i}/{len(changes)}] {path}")
            commit_msg = self._commit_message(path, mode)
            self.azdo.commit_file(
                path=path,
                content=new_content,
                message=commit_msg,
                branch=pr_branch,
            )

        # 3. Build PR body
        file_sections = "\n".join(
            _FILE_SECTION_TEMPLATE.format(
                path=path,
                summary=summaries.get(path, "_No summary available._"),
            )
            for path in changes
        )

        body = _PR_BODY_TEMPLATE.format(
            mode=mode,
            total_files=total_files_analysed or "N/A",
            changed_files=len(changes),
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            file_sections=file_sections,
        )

        title = self._pr_title(mode, len(changes))

        # 4. Open PR
        log.info(f"Opening PR: '{title}'")
        pr_url = self.azdo.create_pull_request(
            title=title,
            body=body,
            head_branch=pr_branch,
            base_branch=base_branch,
        )
        return pr_url

    # ── Helpers ─────────────────────────────────────────────────────────────

    @staticmethod
    def _pr_title(mode: str, n_files: int) -> str:
        mode_labels = {
            "errors": "Bug fixes",
            "optimise": "Performance & readability improvements",
            "both": "Bug fixes + performance improvements",
        }
        label = mode_labels.get(mode, "Code improvements")
        return f"🤖 AI Review: {label} across {n_files} file(s)"

    @staticmethod
    def _commit_message(path: str, mode: str) -> str:
        verbs = {
            "errors": "fix: AI-identified bug fixes",
            "optimise": "refactor: AI performance & readability improvements",
            "both": "fix/refactor: AI code review improvements",
        }
        verb = verbs.get(mode, "chore: AI code review")
        return f"{verb} in {path}"
